cfg = ArtesianServiceConfig("baseAddress","apiKey");
qs = QueryService(cfg);


%AbsoluteRange - TimeZone - MultiIds
test1 = qs.CreateAuction() ...
    .ForMarketData([100181921]) ...
    .InAbsoluteDateRange("2020-03-01","2020-03-20") ...
    .InTimeZone("UTC") ...
    .Execute()
