cfg = ArtesianServiceConfig("baseaddr","apikey");
qs = GMEPublicOfferService(cfg);

%AbsoluteRange - TimeZone - MultiIds
test1 = qs.CreateGMEPublicOfferQuery() ...
    .ForDate("2023-07-22") ...
    .ForPurpose(Purpose.OFF) ...
    .ForStatus(Status.ACC) ...
    .ForMarket(Market.MIXBID) ...
    .Execute()
